name: CI/CD IIS WebDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clone repository via SSH
        shell: cmd
        env:
          GIT_SSH_COMMAND: "\"C:/Program Files/Git/usr/bin/ssh.exe\" -i C:/Windows/ServiceProfiles/NetworkService/.ssh/id_ed25519 -o UserKnownHostsFile=C:/Windows/ServiceProfiles/NetworkService/.ssh/known_hosts -o IdentitiesOnly=yes"
        run: |
          rmdir /s /q . 2>nul
          git clone --depth 1 git@github.com:henriquemoreno/devops-demo.git .

      - name: Restore
        shell: cmd
        run: dotnet restore

      - name: Build
        shell: cmd
        run: dotnet build -c Release --no-restore

      - name: Publish
        shell: cmd
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS via Web Deploy
        shell: cmd
        run: |
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
          -verb:sync ^
          -source:contentPath="%CD%\publish" ^
          -dest:contentPath="C:\inetpub\DevOpsDemo" ^
          -enableRule:AppOffline ^
          -enableRule:BackupRule
