name: CI/CD IIS WebDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Force Git HTTP/1.1
        shell: cmd
        run: git config --global http.version HTTP/1.1

      - name: Clone repository (manual)
        shell: cmd
        run: |
          rmdir /s /q . 2>nul
          git clone --depth 1 https://github.com/henriquemoreno/devops-demo .

      - name: Restore
        shell: cmd
        run: dotnet restore

      - name: Build
        shell: cmd
        run: dotnet build -c Release --no-restore

      - name: Publish
        shell: cmd
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS via Web Deploy
        shell: cmd
        run: |
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
          -verb:sync ^
          -source:contentPath="%CD%\publish" ^
          -dest:contentPath="C:\inetpub\DevOpsDemo" ^
          -enableRule:AppOffline ^
          -enableRule:BackupRule


