name: CI/CD IIS WebDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Force Git HTTP/1.1
        shell: cmd
        run: git config --global http.version HTTP/1.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Deploy to IIS via Web Deploy
        run: >
          "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
          -verb:sync
          -source:contentPath="${{ github.workspace }}\publish"
          -dest:contentPath="C:\inetpub\DevOpsDemo"
          -enableRule:AppOffline
          -enableRule:BackupRule
